### ISSUE TITLE
Allow an environment variable change the list of !!play --random

### ISSUE THREAD

**Issue by V-ed** [Vhoyon/Discord-Bot#121]
The environment key could be `PLAYLISTS_PLAY_RANDOM` and it could use `EnumField` SettingField (without being able to configure it with the setting command) to split the values.

The separators could then be `|` for playlists and `{}` for Name/Source separator. 

The default behavior would then be to overwrite the default playlists that we provide in the code. This means we could potentially add another environment variable to allow for a simple addition to the in-code playlists. This environment variable could be keyed `PLAYLISTS_PLAY_OVERWRITE`, which the default behavior would be `true`.

**Comment by StephanoMehawej** [comment]
I would like more info on this please. I am not really sure i understand what is requested here.
