### ISSUE TITLE
Tweak CommandClear to add a flag that tells user that everything has been cleared

### ISSUE THREAD

**Issue by V-ed** [Vhoyon/Discord-Bot#140]
Currently, the bot sends the message `Cleared everything!` after clearing everything (or having sent the request to clear everything).

It would be better to not show this message by default and add a flag that tells the bot to send this message : the flag could be `-n` for `--notify`.

**Comment by StephanoMehawej** [comment]
So basically make the message show only when the -n tag is used?

**Comment by V-ed** [comment]
@StephanoMehawej Yes.
