### ISSUE TITLE
Trying to play music in another VoiceChannel should tell the user that the bot cannot be on two VoiceChannel and to move to that channel

### ISSUE THREAD

**Issue by V-ed** [Vhoyon/Discord-Bot#147]
Because a single bot cannot be in two VoiceChannel at the same time, if a server is already playing some music, our bot wouldn't be able to play both at the same time.

Therefore, we should send a message telling the other user that tries to make the bot join them to go to the VoiceChannel where the bot is currently playing some music.

In the case where the bot is alone and not yet disconnected, we should switch the bot to the new VoiceChannel instead of telling the user to come to the bot's channel.

**Comment by StephanoMehawej** [comment]
I am not sure if the bot should move if it is already connected to a voice channel

**Comment by V-ed** [comment]
@StephanoMehawej It should not indeed : if a user is in another voice channel than our bot when trying to play a track, a message should be sent saying that the _user_ should switch because the bot cannot be in two voice channel at the same time.
