### ISSUE TITLE
Clear for a single user throws an error

### ISSUE THREAD

**Issue by StephanoMehawej** [Vhoyon/Discord-Bot#150]
When you try to clear a user's message with <code>\clear -u [@user]</code> the bot does not respond and throws the following error in the terminal: <code>[ERROR] [tried to log empty message]</code>

**Comment by V-ed** [comment]
Just to give some pointers on where to start debugging this, you'll want to put a breakpoint on this line :
https://github.com/Vhoyon/Discord-Bot/blob/889fe418e644e03ffbd9ac48ac87091bda59f594/framework/vendor/modules/Logger.java#L162 and look up the stacktrace to have a better understanding of the context where this error happens.

I've looked at the code and I can't find the issue directly - it's probably some debugging shenanigans, but the fact that the bot does nothing on the command `\clear -u [@user]` tells me there's a crash happening somewhere and I can't tell where.

This really makes me want to implement a way to know, when the logger logs an error, to get the line number & class where the `log` call was made...
https://stackoverflow.com/questions/31128053/get-line-number-of-method-caller

**Comment by V-ed** [comment]
Also, ref #12

**Comment by StephanoMehawej** [comment]
thanks for the info
