### ISSUE TITLE
Stopping the spam command does nothing

### ISSUE THREAD

**Issue by StephanoMehawej** [Vhoyon/Discord-Bot#174]
When you try to stop the spam command that was sent to a specific user, it tells you it stopped but it does not stop.

**Comment by V-ed** [comment]
Just to be sure I understand correctly, you are not trying to stop the spam from within the private channel with the bot, but rather in the TextChannel that you entered the original spam command, is this correct?

**Comment by StephanoMehawej** [comment]
I did indeed try to stop it in the TextChannel where I entered the original spam.

**Comment by V-ed** [comment]
The spam command cannot stop, despite sending out a message that is has successfully stopped.

To be investigated.
