### ISSUE TITLE
Disconnect delay when empty should not send a message if nobody is in the VoiceChannel anymore

### ISSUE THREAD

**Issue by V-ed** [Vhoyon/Discord-Bot#196]
After PR #193 was merged, a new feature was added to diconnect the bot when not playing for a certain delay.

After this delay however, a message is sent to notify users why the bot disconnected : `~~ Disconnected due to inactivity ~~`.

This message is neat when users are still there, but when nobody is in the VoiceChannel anymore, it makes no sense that the bot tells that he's disconnecting (*who is he saying it to?*).

We should check how many people are in the server and if no **human** is in the connected VoiceChannel, then don't send the message when disconnecting.

**Comment by StephanoMehawej** [comment]
@V-ed At that point, the disconnect when a voice channel is empty should apply
