### ISSUE TITLE
Make the bot disconnect after a little delay when it is playing music and no one is in the voice channel anymore

### ISSUE THREAD

**Issue by V-ed** [Vhoyon/Discord-Bot#31]
The delay could be configurable by the `settings` command (and therefore also by the environment) and could default to `15000` milliseconds (equivalent of 15 seconds).

There would be a need to intercept the event triggered when a user leave, and if the channel in question is the one where the bot is connected to, test if the number of user remaining is equals to one (aka only the bot remaining), start the delay and a scope variable `toDisconnect` so if no interruption is done after the delay, disconnect the bot.

If a user joins back before the delay end, the interraction is stopped and the bot doesn't disconnect.

EDIT :
- name of the setting should be `alone_drop_delay`
- env of the setting should be `MUSIC_ALONE_DISCONNECT_DELAY`

**Comment by V-ed** [comment]
@StephanoMehawej
> Why does the MusicPlayer need the command?

This was made initially to get easy access to the Guild (we already store it in the BotCommand) and its utility methods (`command.disconnect()`).

However, it is not mandatory and we could (and will need to anyway for this issue to be fixed) to refactor to remove all uses of BotCommand and instead use the Guild object directly.

I'll see if I can make a more generic MessageEventDigger, as such utility class is quite useful for more intense event digging - I'll see that later, probably in the month of november.

In the mean time, can you refactor Musicmanager and MusicPlayer to remove every BotCommand references? If you want me to do it, don't hesitate to notify me!

**Comment by StephanoMehawej** [comment]
@V-ed 

As we use the command in the MusicPlayer to set the volume, it will probably require a refactor of the way we set the settings then.

**Comment by V-ed** [comment]
@StephanoMehawej Not by changing how we store settings, but rather how we set the default volume.

Instead of getting the setting value in MusicPlayer, we should send the default volume to the constructor directly.

Therefore, when calling loadTrack, we would also send the default volume as parameter.

This will then allow for external sources to load tracks with the same flexibility as command.

We can also keep the constructors with BotCommand in MusicPlayer, but the former will get the Guild and default volume and simply call the new constructor (with the Guild and default volume parameters).

How does that sounds?

**Comment by StephanoMehawej** [comment]
Good but confusing

**Comment by V-ed** [comment]
@StephanoMehawej How so?

This way, the change will be backward compatible, faster to type in commands, and allow for external modifications...

**Comment by StephanoMehawej** [comment]
@V-ed 

To what constructor exactly?

**Comment by V-ed** [comment]
@StephanoMehawej I'm saying we should create a new constructor under MusicPlayer (with the AudioPlayer, Guild and default volume) _and_ keep the old constructor (with the AudioPlayer and BotCommand), but now the old constructor would simply call the logic of the new constructor with `this(audioPlayer, command.getGuild(), command.setting("volume")`.

**Comment by StephanoMehawej** [comment]
Ahhhhhhh
i see
