### ISSUE TITLE
Add a way to play the latest played song

### ISSUE THREAD

**Issue by V-ed** [Vhoyon/Discord-Bot#60]
This command could be like `!!play --l` or `!!replay`.

**Comment by StephanoMehawej** [comment]
That's for the previous song?

**Comment by StephanoMehawej** [comment]
I would save the previous song but if there is none, I would maybe play the last song but that sounds a lot like replay to me

**Comment by V-ed** [comment]
Yeah, a replay is basically what this issue is about :)

If there is no previous song, just send a message telling the user that there is no previous song, you can't make stuff appear from tin air ;)
